In [24]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [25]:
from tensor_completion import loss, norm, utils
import numpy as np

In [13]:
# Create a simple 3rd order tensor
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
X0 = utils.unfold(X, 0)
X1 = utils.unfold(X, 1)
X2 = utils.unfold(X, 2)

print('Shape of X: ', X.shape)
print('------------------')
print('Shape of X0: ', X0.shape)
print('Shape of X1: ', X1.shape)
print('Shape of X2: ', X2.shape)

X0, X1, X2

Shape of X:  (2, 3, 4)
------------------
Shape of X0:  (2, 12)
Shape of X1:  (3, 8)
Shape of X2:  (4, 6)


(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]]),
 array([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]]))

In [46]:
Xfold0 = utils.fold(X0, 0, X.shape)
Xfold1 = utils.fold(X1, 1, X.shape)
Xfold2 = utils.fold(X2, 2, X.shape)

print('Shape of Xfold0: ', Xfold0.shape)
print('Shape of Xfold1: ', Xfold1.shape)
print('Shape of Xfold2: ', Xfold2.shape)

Xfold0, Xfold1, Xfold2

Shape of Xfold0:  (2, 3, 4)
Shape of Xfold1:  (2, 3, 4)
Shape of Xfold2:  (2, 3, 4)


(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [21]:
tnn = norm.tensor_nuclear_norm(X)

nn0 = norm.nucleus_norm(X0)
nn1 = norm.nucleus_norm(X1)
nn2 = norm.nucleus_norm(X2)

sv0 = np.linalg.svd(X0, compute_uv=False)
sv1 = np.linalg.svd(X1, compute_uv=False)
sv2 = np.linalg.svd(X2, compute_uv=False)

print('Tensor nuclear norm: ', tnn)
print('------------------')
print('Nucleus norm of X0: ', nn0)
print('Nucleus norm of X1: ', nn1)
print('Nucleus norm of X2: ', nn2)
print()
print('Singular values of X0: ', sv0.round(2))
print('Singular values of X1: ', sv1.round(2))
print('Singular values of X2: ', sv2.round(2))

Tensor nuclear norm:  68.48799935460568
------------------
Nucleus norm of X0:  72.92592905480178
Nucleus norm of X1:  72.66907628981167
Nucleus norm of X2:  68.48799935460568

Singular values of X0:  [65.32  7.61]
Singular values of X1:  [65.35  7.32  0.  ]
Singular values of X2:  [65.7   2.79  0.    0.  ]


In [37]:
# Create a simple matrix
Z = np.arange(12).reshape(3, 4)

# Create a simple coefficient matrix
A = np.arange(9).reshape(3, 3)

# Create a simple lag set of indices
h_indices = np.array([0, 1, 2])


diff = Z.copy()
for m in range(len(Z)):
    for t in range(len(Z[0])):
        for i in range(len(h_indices)):
            diff[m][t] -= A[m][i] * Z[m][t - h_indices[i]]

print('Verification of the NumPy implementation of the autoregressive norm:')
print("- for loops :", np.sum(diff**2))
print("- numpy :", norm.autoregressive_norm(Z, A, h_indices))

Verification of the NumPy implementation of the autoregressive norm:
- for loops : 159494
- numpy : 159494
